name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"       # tiap hari 00:00 UTC
  workflow_dispatch:           # bisa dijalankan manual

permissions:
  contents: write              # <-- penting, biar bisa commit/push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: KarboLennon
          outputs: |
            dist/snake.svg

      - name: Commit & push snake.svg
        run: |
          mkdir -p output
          cp dist/snake.svg output/snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "chore: update snake" || echo "no changes"
          git push
